remote_theme: pmarsceill/just-the-docs
title: TuxJSQL-SQLITE
description: Tuxjsql SQLITE documentation
url: "https://tuxjsql.dev"
baseurl: "/sqlite/"
aux_links:
  "TuxJSQL GitHub":
    - "//github.com/tuxjsql"